### ISSUE TITLE
Breaks cross-origin links without an explicit `target` attribute

### ISSUE THREAD

**Issue by nc7s** [Kalabasa/htmz#1]
… which then can not be opened. Tested with the [GitHub] link of the doc page, on Firefox and Chrome.

**Comment by lpil** [comment]
Hello! Could you go into more detail on this? I'm not the maintainer but I was curious as to what you meant and I wasn't able to reproduce the issue.

**Comment by nc7s** [comment]
> reproduce the issue

1. Open http://leanrada.com/htmz/
2. Right click the [GitHub] link, inspect element
3. Remove the `target` attribute in the Inspector (deleting its value is enough)
4. Switch to the Console tab
5. Click the link and see what happens

**Comment by Kalabasa** [comment]
I think it is specific to that page, because that page has a `<base target=htmz>` tag. Removing `target="_blank"` would make the link default to `target="htmz"`, then htmz tries to extract DOM nodes from GitHub which is naturally forbidden.

Do you have a different test case?

**Comment by nc7s** [comment]
It seems so. TIL and thanks for introducing `<base>` ;)
