### ISSUE TITLE
Support for consecative GET requests to the same resource URL

### ISSUE THREAD

**Issue by jmcudd** [Kalabasa/htmz#13]
The default htmz snippet doesn't support multiple requests to the same resource URL. There are a couple workarounds to this, one is to make resource URL unique with query parameters, but ideally htmz would just handle this out of the box and make the same request twice. Below is an example of how to achieve this.

```javascript
<script>
function htmz(frame){
  setTimeout(()=>{
    if(frame.contentWindow.location=='about:blank') return; //Don't load blank page, and avoid infinite loop.

    document.querySelector(frame.contentWindow.location.hash||null)?.replaceWith(...frame.contentDocument.body.childNodes);
    
    frame.contentWindow.location='about:blank'; //clear iframe after load.
  })
}
</script>
<iframe hidden name=htmz onload="htmz(this)"></iframe>
```

Without setting the `location` to `about:blank` after the replacement, a link would only load once and consecative clicks would be ignored since the resourceURL didn't change.

Anyway, Not sure if this merits a example, or maybe there is a cleaner technique.

**Comment by XCanG** [comment]
When I looking at demos, the first issue I was thinking about is concurrency. Now, while I wouldn't use it in any serious project, when it come to do some expensive requests that may take, for example 300 ms, there is a chance that user could be in a hurry and will clicking on the other part of UI elements. Now, because there is only one iframe it seems like there is a possibility to cancel that request by requesting different one before previous get a response.

**Comment by jmcudd** [comment]
> When I looking at demos, the first issue I was thinking about is concurrency. Now, while I wouldn't use it in any serious project, when it come to do some expensive requests that may take, for example 300 ms, there is a chance that user could be in a hurry and will clicking on the other part of UI elements. Now, because there is only one iframe it seems like there is a possibility to cancel that request by requesting different one before previous get a response.

Yeah this merely fixes the issue of making the exact same request a second time and expecting a request to be made by the frame. It doesn't address the issue of concurrent requests.

I believe you would have to use multiple iframes to handle multiple requests and deal with conflicting targets.

**Comment by Kalabasa** [comment]
It does support repeated requests if you use POST (i.e. a form).

I actually almost included the same `about:blank` thing in the snippet, but I decided to lean on standards as a principle and as a way to minimize size.

Standards say that GET is cachecable, so repeated GET requests may not be fully requested by the browser. In a way the above issue is expected.

> The response to a GET request is cacheable; a cache MAY use it to satisfy subsequent GET and HEAD requests unless otherwise indicated by the Cache-Control header field ([Section 5.2](https://www.rfc-editor.org/rfc/rfc9111#section-5.2) of [[CACHING](https://www.rfc-editor.org/rfc/rfc9110.html#CACHING)]).

Meanwhile POSTs usually don't get cached.

However, I think I would include this as an example. I'm thinking of collecting these extensions into a separate page.

**Comment by jmcudd** [comment]
Oh that makes _a lot_ of sense, certainly in the spirit of this project too! If someone wanted to bust the cache on a GET request and stick with the standards I believe they could add this to their responses, however I'm not sure it would fix the issue due to the way the iframe url is updated:

```
Expires: Tue, 03 Jul 2001 06:00:00 GMT
Last-Modified: {now} GMT
Cache-Control: max-age=0, no-cache, must-revalidate, proxy-revalidate
```
Source: https://stackoverflow.com/a/9886945

**Comment by Kalabasa** [comment]
I've added your `about:blank` solution to the new [Extensions page](https://leanrada.com/htmz/extensions/), if you don't mind. I modified the cleanup method to be `replace("about:blank")` so it doesn't add an extra history entry.
