### ISSUE TITLE
$_REQUEST only for PHP?

### ISSUE THREAD

**Issue by otengkwame** [Kalabasa/htmz#15]
Is the $_REQUEST php global array the only one to use?

**Comment by Kalabasa** [comment]
@Malix-off Thanks for the suggestion, I opened the discussions tab.

@otengkwame Well, backend details are not really relevant to htmz. So, I guess the answer to your question would be: no.

**Comment by Malix-off** [comment]
@Kalabasa btw, already created issues can be converted to https://github.com/Kalabasa/htmz/discussions (and also [this comment](https://github.com/Kalabasa/htmz/issues/15#issuecomment-1956571056) can be marked as an answer)
