### ISSUE TITLE
Support IE 11

### ISSUE THREAD

**Issue by niutech** [Kalabasa/htmz#17]
In order to support older browser such as IE 11, you could rewrite the onclick handler to:

    setTimeout(function(){(document.querySelector(contentWindow.location.hash||null)||{}).outerHTML=contentDocument.body.innerHTML})

**Comment by Kalabasa** [comment]
Just want to point out `outerHTML` re: security.

`outerHTML` would let the child page execute scripts in the parent domain, which is something to keep in mind if links can be user-generated.

I've removed `outerHTML` references in my examples because of this.

**Comment by Malix-off** [comment]
Even jQuery v4 and HTMX v2 dropped IE 11 support
I think it's preferable to also not refactor to support it
