### ISSUE TITLE
Clean target values approach not working

### ISSUE THREAD

**Issue by fractaledmind** [Kalabasa/htmz#18]
Using the `htmz` function defined in a script tag isn't working in either Chrome or Safari for me. 

Code:
```html
<iframe hidden src="/tasks/1#hello" id="hello" name=htmz onload="htmz(this)"></iframe>
<script type="text/javascript">
  function htmz(frame) {
    document.querySelector(frame.name) // use the iframe's name instead of the URL hash
      ?.replaceWith(...frame.contentDocument.body.children);
  }
</script>
```

Errors:
```
# Safari
TypeError: htmz is not a function. (In 'htmz(this)', 'htmz' is an instance of Window)
# Chrome
Uncaught TypeError: htmz is not a function
    at HTMLIFrameElement.onload
```

No Content Security Policy is being used. I'm not sure what could be wrong here. Any guidance?

**Comment by fractaledmind** [comment]
Learned a couple of things:

1. `onload` is always called when the iframe is first rendered on the page
2. when the iframe has a `src`, it is loaded before the `script` is available, even if the script is before the iframe or even in the `head`

**Comment by fractaledmind** [comment]
I was experimenting with lazy loading content. So, the iframe replaces itself with the content from `src` after that is fetched. I've been exploring how to expand the possible use cases for the core htmz idea of leaning on iframes to drive a kind of HTML-AJAX

**Comment by Kalabasa** [comment]
Does it fire `onload` with `about:blank` as the `contentWindow.location`? I found that `onload`s get called on first render, but with blank documents. In those cases, I would guard the htmz function with `if (frame.contentWindow.location.href === 'about:blank') return`.

**Comment by Kalabasa** [comment]
I just realized that you're trying to use the iframe concept as "partials" instead of an onclick-response-handler thing. I'll close this issue as it is out of the scope - htmz is not an HTML includes / partials library that executes on page load.

By the way, I just came across this article (the code is in English), which does what you want https://zenn.dev/kawarimidoll/articles/33316cf9caa465
