### ISSUE TITLE
Using htmz without updating browser history

### ISSUE THREAD

**Issue by lpil** [Kalabasa/htmz#2]
Hello!

Thanks for this library! It's very cool.

Do you have a recommendation or an extension for not adding to the browser history when clicking on htmz links? I'd like my back button to (for example) go to what my user sees as the previous page rather than resetting a form to a previous state.

Thanks,
Louis

**Comment by Kalabasa** [comment]
I discovered this by accident.

In the `cf_clean_target_tabs` example. There are named iframes for each destination, following the "Clean target values" approach. These iframes are _inside_ the target elements, meaning they get replaced everytime the target updates.

Apparently, removing an iframe deletes its browser history from your global browser history. So the `cf_clean_target_tabs` example doesn't record history!

As for a non-accidental solution, unfortunately I don't have any idea other than asking whatwg for a native HTML way.

**Comment by drmercer** [comment]
Maybe the iframe could destroy and recreate itself after every action? Interestingly, that would solve #13 as well I think

**Comment by Malix-off** [comment]
@drmercer indeed, but I don't think it's a good idea performance-wise.
No idea if it would break some part of the previous history too.

**Comment by Kalabasa** [comment]
Explicitly destroying & recreating the iframe sounds feasible

Maybe even simply removing & reinserting the node instead of recreating from scratch as suggested here https://stackoverflow.com/a/25365973/3144156

I think I might need a separate page to collect these extensions.

**Comment by niutech** [comment]
Why not just use [<object> tags](https://stackoverflow.com/a/32854559)?

**Comment by Kalabasa** [comment]
I just tried `<object>`, and `<embed>`. Unfortunately we can't target those elements with the `target` attribute.

**Comment by Kalabasa** [comment]
> simply removing & reinserting the node

I've added this solution in the brand new [Extensions page](https://leanrada.com/htmz/extensions/)!

**Comment by lpil** [comment]
Brilliant! Thank you so much @Kalabasa 💜 

The page looks great too
